Environments:
  - Name: prd
    ApproverGroups:
      - Name: Group A
        Approvers:
          - Name: Alice
            Email: alice@example.com
        RequiredApprovals: 1
      - Name: Group B
        Approvers:
          - Name: Bob
            Email: mvanoudheusden@gmail.com
          - Name: Charlie
            Email: charlie@example.com
        RequiredApprovals: 2
    SelfApprovalAllowed: false
    time_restriction:
      start_time: "18:00"
      end_time: "08:00"
      additional_approvers:
        - name: Manager
          email: manager@example.com
  - Name: staging
    ApproverGroups:
      - Name: Group C
        Approvers:
          - Name: David
            Email: david@example.com
        RequiredApprovals: 1
    SelfApprovalAllowed: true
