name: Release [main] to prd

# Controls when the action will run. 
on:
  release:
    types: [published]

jobs:
  deploy_prd:  
    name: Deploy to Production
    concurrency: production_environment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: prd
    steps:
      - name: "Output"
        run: |
         echo "${GITHUB_ACTOR}"

