name: Release [main] to prd

# Controls when the action will run. 
on:
  release:
    types: [published]

jobs:
  deploy_prd:  
    name: Deploy to Production
    concurrency: production_environment
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 
      name: prd
    steps:
      - name: "Output"
        run: |
         echo "${GITHUB_ACTOR}"
         echo $RUNID
        env:
          RUNID: ${{ github.run_id }}
      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
            console.log(context.actor)
            const approvals = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            })

            console.log(approvals.data)

            approvals.data.forEach(element => {
                if (element.user.login == context.actor)
                  core.setFailed(`Deployment to the environment is approved by the same person (${context.actor}) who initiated the deployment. This is not allowed.`);            
              });

